- hosts: test-vps1
  gather_facts: yes
  remote_user: ma-sa
  tasks:
    - name: Install the package git
      apt:
        name: git
        state: present
      become: true
    - name: Install the package build-essential for gcc
      apt:
        name: build-essential
        state: present
      become: true
    - name: Install the package zlib
      apt:
        name: zlib1g-dev
        state: present
      become: true
    - name: Clone a pyenv repository
      git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: /home/ma-sa/.pyenv
    - name: Delete bash_profile
      file:
        path: "{{ ansible_env.HOME }}/.bash_profile"
        state: absent
    - name: Define environment variable PYENV_ROOT
      shell: |
        echo 'export PYENV_ROOT="{{ ansible_env.HOME }}/.pyenv"' >> {{ ansible_env.HOME }}/.bash_profile
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> {{ ansible_env.HOME }}/.bash_profile
      args:
        executable: /bin/bash 
    - name: Add pyenv init
      shell: | 
        echo 'eval "$(pyenv init -)"' >> {{ ansible_env.HOME }}/.bash_profile 
      args:
        executable: /bin/bash 
    - name: Install lib-ssl-dev
      apt:
        name: libssl-dev
        state: present 
      become: true
    - name: Install Python by Pyenv
      shell: /bin/bash -lc "pyenv install -s 3.6.2"
    - name: change Global python version
      shell: /bin/bash -lc "pyenv global 3.6.2"
